### ISSUE TITLE
idk what to do

### ISSUE THREAD

**Issue by hhjjj75** [utkusen/shotlooter#11]
C:\Users\admin\Downloads\shotlooter-master>python shotlooter.py --code hd8375 --imagedir img
Analyzing: hd8376
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd8376.png'
Analyzing: hd8377
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd8377.png'
Analyzing: hd8378
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd8378.png'
Analyzing: hd8379
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd8379.png'
Analyzing: hd837a
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd837a.png'
Analyzing: hd837b
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd837b.png'
Analyzing: hd837c
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd837c.png'
Analyzing: hd837d
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd837d.png'
Analyzing: hd837e
[Errno 2] No such file or directory: 'C:\\Users\\admin\\Downloads\\shotlooter-master/output/hd837e.png'

For some reason it try to open files that doesnt exist

**Comment by georgettica** [comment]
This might be realted to not using platform agnostic file path here
https://github.com/utkusen/shotlooter/blob/e7a64c944be4981f0fd35c8520679176f1383bc8/shotlooter.py#L169

You can follow this in order to make it agnostic
https://www.geeksforgeeks.org/python-os-path-join-method/

**Comment by georgettica** [comment]
Was it solved?
I am asking as I invested time debugging

**Comment by hhjjj75** [comment]
> Was it solved?
> I am asking as I invested time debugging 

Yes.
Sorry it took long To answer but i forgot my gh password

**Comment by georgettica** [comment]
Happens to the best and worst of us.

Stay safe and be well!

**Comment by hhjjj75** [comment]
👍

ke 9. maalisk. 2022 klo 4.35 Ron Green ***@***.***> kirjoitti:
