### ISSUE TITLE
opencv on raspberry pi

### ISSUE THREAD

**Issue by pispuso** [utkusen/shotlooter#2]
It's not really an error related to shotlooter but just in case anyone else is having problems. On Kali Linux 2020.2 for Raspberry Pi you wont be able to install opencv-python since there is no official release for raspberry pi architecture.

Sadly I get this error when installing requirements:

Could not find a version that satisfies the requirement opencv-python-headless

Anyway, just that. If I find a solution I'll update this.

**Comment by utkusen** [comment]
Unfortunately, this is not a problem that I can solve :/

**Comment by pispuso** [comment]
> Unfortunately, this is not a problem that I can solve :/

That's ok, as I said, this was just as a placeholder if anyone else is having this problem on a raspberry, i'll try to make it work and post a solution.

Other than this, shotlooter is working wonders on my laptop. Amazing project!

Thanks!
