### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by sjj2004** [utkusen/shotlooter#7]
does it on win10 and mac os, it was running fine and working properly and all of a sudden on both my windows machine and my mac, it reads index out of range and i cant get it to work again, happened exactly the same time on both devices

**Comment by sjj2004** [comment]
ok it appears prnt.sc has banned my IP lol, maybe something to be aware of everyone. Might be cos i was running several instances so one might be ok.

**Comment by sjj2004** [comment]
Reset router and sorted.

**Comment by grogloog** [comment]
I`ve got the same thing. It seems that lightshot`s developers finally decided to do something with that breach.
